@startuml
actor teachers

teachers -> courses_resource:获取课程库
courses_resource -> courses:选择开课
opt 学院已开课
teachers ->courses_resource
courses_resource -> courses:选择课程
courses-->teachers:返回课程信息
end
@enduml