   @startuml
    object 读者 {
        姓名="吴宇峰"
        身份证号=111111111
        借书卡号=201510414319
        借书限额=10
        可借限额=5
    }
    object 借书记录{
        借书日期=2018-04-16
        应还日期=2018-05-16
        还书日期=2018-05-06
    }
    object 图书{
        馆藏流水号=20180416
        状态="借出"
    }
    object 图书品种{
        书名="信息系统分析与设计"
        作者="王晓敏 邝孔武"
        出版社="清华大学出版社"
        出版日期=1998-06
        国际出版号="978-7-302-32982-4"
        价格=45.00
    }
    object 图书管理员{
        职工号=0000001
        姓名="吴天峰"
    }
    读者 -- 借书记录
    图书品种 -- 图书
    图书 -- 借书记录
    图书管理员 -- 借书记录
    @enduml